"""edit base

Revision ID: 1e183ad8e38d
Revises: a41e8d1774d7
Create Date: 2023-12-03 21:39:48.453937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e183ad8e38d'
down_revision = 'a41e8d1774d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
