"""edit base

Revision ID: 42cc657497f0
Revises: c1bd787f10d0
Create Date: 2023-12-03 19:55:38.772921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42cc657497f0'
down_revision = 'c1bd787f10d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
