"""edit base create camera table

Revision ID: 4b85520f9cc4
Revises: 5a239e71eb86
Create Date: 2023-12-05 01:01:09.789431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b85520f9cc4'
down_revision = '5a239e71eb86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
