"""edit base create camera table

Revision ID: 5a239e71eb86
Revises: a9676aad2cd9
Create Date: 2023-12-05 00:58:00.472092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a239e71eb86'
down_revision = 'a9676aad2cd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superadmin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superadmin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
