"""edit base create camera table

Revision ID: 7b6fcbd65ac5
Revises: 1e183ad8e38d
Create Date: 2023-12-04 22:04:56.513228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b6fcbd65ac5'
down_revision = '1e183ad8e38d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
