"""edit base

Revision ID: c1bd787f10d0
Revises: eb9f15c8d236
Create Date: 2023-12-03 19:53:49.571269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1bd787f10d0'
down_revision = 'eb9f15c8d236'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cameras_id', table_name='cameras')
    op.drop_index('ix_cameras_title', table_name='cameras')
    op.drop_table('cameras')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cameras_pkey')
    )
    op.create_index('ix_cameras_title', 'cameras', ['title'], unique=False)
    op.create_index('ix_cameras_id', 'cameras', ['id'], unique=False)
    # ### end Alembic commands ###
